Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -29,7 +29,7 @@ jobs:
         try:
             with open('infra/config/app_config.yaml', 'r') as config_file:
                 config = yaml.safe_load(config_file)
-                docker_image_name = config.get('docker_image_name', 'default_image_name')
+                docker_image_name = config.get('docker_image_name', 'defaultimagename')
                 if not docker_image_name:
                     raise ValueError('Docker image name is not defined in app_config.yaml')
                 print(docker_image_name)
@@ -43,6 +43,10 @@ jobs:
             print(f'Error: {str(e)}')
             exit(1)
         ")
+        if [ -z "$DOCKER_IMAGE_NAME" ]; then
+            echo "Error: Docker image name is empty."
+            exit 1
+        fi
         docker build -t $DOCKER_IMAGE_NAME -f infra/docker/Dockerfile .
 
     - name: Print Docker image name
